name: numbers_game
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=2.0.0-dev.68.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.2
  screen: ^0.0.4
  flutter_simple_dependency_injection: ^0.0.5
  shared_preferences: ^0.4.3
  swipedetector: ^1.2.0
  collection: ^1.14.11

dev_dependencies:
  flutter_test:
    sdk: flutter


flutter:

  uses-material-design: true
